// Drizzle regenerates a full schema snapshot per migration — 10k+ lines of
// JSON that no reviewer reads and that would dwarf the rest of the diff.
const GENERATED = /(^|\/)meta\/(_journal|\d+_snapshot)\.json$/;

export function stripGeneratedFiles(diff: string): string {
  const sections = diff.split(/^(?=diff --git )/m);
  const dropped: string[] = [];
  const kept = sections.filter((section) => {
    const path = section.match(/^diff --git a\/(.+?) b\//)?.[1];
    if (!path || !GENERATED.test(path)) return true;
    dropped.push(path);
    return false;
  });
  if (!dropped.length) return diff;
  return `${kept.join("")}\n(omitted from this diff, generated by drizzle: ${dropped.join(", ")})\n`;
}

// Line-anchored review comments are rejected (422) unless the line is part of
// the PR's diff, and one bad anchor fails the whole review — so anchors are
// checked against the diff before submitting.
// Maps each changed file to the new-file line numbers inside its hunks
// (added and context lines; deleted lines exist only on the old side).
export function commentableLines(diff: string): Map<string, Set<number>> {
  const byPath = new Map<string, Set<number>>();
  let lines: Set<number> | undefined;
  let newLine = 0;
  for (const line of diff.split("\n")) {
    const fileHeader = line.match(/^\+\+\+ b\/(.+)$/);
    if (fileHeader) {
      lines = new Set();
      byPath.set(fileHeader[1]!, lines);
      continue;
    }
    const hunk = line.match(/^@@ -\d+(?:,\d+)? \+(\d+)/);
    if (hunk) {
      newLine = Number(hunk[1]);
      continue;
    }
    if (!lines) continue;
    if (line.startsWith("+") || line.startsWith(" ")) lines.add(newLine++);
  }
  return byPath;
}
